# Site settings
title: VoterVOX | Building Access, Building Community
email: info@votervox.org
description: > # this means to ignore newlines until "baseurl:"
  VoterVOX makes voting possible for millions of citizens who face language barriers or feel intimidated by the process of exercising their rights. By connecting people to help each other and building a collective resource for ballot translation, VoterVOX will increase voter turnout and civic participation for millions of people.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://votervox.org" # the base hostname & protocol for your site
twitter_username: votervox
github_username:  18mr
facebook_url: https://www.facebook.com/votervox

# Build settings
markdown: kramdown
