module MatchesHelper
	STATUS_PROPOSED = 0
	STATUS_ACCEPTED = 1
	STATUS_VOLUNTEER_DECLINED = 2
	STATUS_VOTER_DECLINED = 3
	STATUS_COMPLETED = 4

	PROPOSAL_INTERACTION = 0
	RESCHEDULE_INTERACTION = 1
	ASSISTANCE_INTERACTION = 2
end
